class Endpoints:
    AUTH_TOKEN_URL = "https://api.tassbeeh.com/api/v1/auth/authenticate"
    REGISTER_TAPS_URL = "https://api.tassbeeh.com/api/v1/game/register-taps"
    PROFILE_URL = "https://api.tassbeeh.com/api/v1/game/profile"
    CHECK_IN_URL = "https://api.tassbeeh.com/api/v1/game/check-in"
    REFILL_ENERGY_URL = "https://api.tassbeeh.com/api/v1/energy/refill-energy"
    PRAYER_STATUS_URL = "https://api.tassbeeh.com/api/v1/energy/prayer-status"
    QUESTS_URL = "https://api.tassbeeh.com/api/v1/quests/all"
    VERIFY_QUEST_URL = "https://api.tassbeeh.com/api/v1/quests/verify"
    AD_BOOSTER_URL = "https://api.tassbeeh.com/api/v1/marketplace/ad-booster"
